# docker-compose.ymlフォーマットのバージョン指定
version: '3'
services:
  # Railsコンテナ定義
  web_s:
    # Dockerfileを使用してイメージをビルド
    build: .
    # コンテナ起動時のデフォルトコマンド
    # ポート番号：3030
    # バインドするIPアドレス：0.0.0.0
    # ポート3030が来たらrailsサーバーが応答
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3030 -b '0.0.0.0'"
    volumes:
      - .:/myapp_s:cached
      # cachedは、コンテナからホストへの書き込みはすぐだが、ホストからコンテナへの書き込みは遅延が許可される
    ports:
      - "3030:3030"
    # dbコンテナが先に起動するよう設定
    depends_on:
      - db_s
    # コンテナを起動しっぱなしにできる
    tty: true
    # pryを使用してデバッグができるよう設定
    stdin_open: true
  # MySQLコンテナ定義
  db_s:
    # mysqlを使用してコンテナ作成
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql
    # ローカル環境とDocker環境のポートフォワーディングを設定
    ports:
      - "3336:3336"
    # コンテナ内の環境変数を定義
    environment:
      # オプション。データベースの名前を指定
      MYSQL_DATABASE: app_development
      # MySQLにおけるスーパユーザのrootアカウントに設定するパスワードを指定
      MYSQL_ROOT_PASSWORD: password